export const CHANGE_FRIEND_LIST_PAGE_NUMBER = "CHANGE_FRIEND_LIST_PAGE_NUMBER";
export const FOLLOW_USER_SUCCESS = "FOLLOW_USER_SUCCESS";
export const FETCH_FRIENDS_SUCCESS = "FETCH_FRIENDS_SUCCESS";
