service: GitMax

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs4.3
  stage: prod
#  stage: dev
  region: us-west-2

plugins:
  - serverless-client-s3

custom:
  client:
    bucketName: www.gitmax.cn
