service: GitMax

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

custom:
  defaultStage: dev

provider:
  name: aws
  runtime: nodejs4.3
  stage: ${opt:stage, self:custom.defaultStage}
  # Deploys to dev stage by default.
  # To deploy for production, run 'serverless deploy --stage production'
  profile: ${self:provider.stage}Profile
  region: us-west-2

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-west-2:*:*"
    - Effect: Allow
      Action:
        - dynamodb:DescribeStream
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:ListStreams
      Resource: "arn:aws:dynamodb:us-west-2:*:table/test"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  addUser:
    handler: users.addUser
    memorySize: 128 # optional, default is 1024
    timeout: 10 # optional, default is 6
    events:
      - http:
          path: addUser
          method: post
          cors: true
#          integration: lambda
#          request:
#            parameters:
#              querystrings:
#                url: true
  followUsers:
    handler: users.followUsers
    memorySize: 512 # optional, default is 1024
    timeout: 60 # optional, default is 6
    events:
#      - stream: arn:aws:dynamodb:us-west-2:151302725877:table/Users/stream/2016-12-16T22:04:17.359
#      - stream: arn:aws:dynamodb:us-west-2:151302725877:table/Friends/stream/2016-12-15T06:46:56.327

  loginStart:
    handler: login.loginStart
    events:
      - http:
          path: loginStart
          method: get
          cors: true
  getToken:
    handler: login.getToken
    environment:
      STAGE: ${self:provider.stage}
      variableValue: 123
    events:
      - http:
          path: getToken
          method: get
          cors: true


# 当前实用的resource - you can add CloudFormation resource templates here

#resources:
#  Resources:
#    UsersTable:
#      Type: 'AWS::DynamoDB::Table'
#      DeletionPolicy: Retain
#      Properties:
#        AttributeDefinitions:
#          -
#            AttributeName: id
#            AttributeType: S
#        KeySchema:
#          -
#            AttributeName: id
#            KeyType: HASH
#        ProvisionedThroughput:
#          ReadCapacityUnits: 10
#          WriteCapacityUnits: 10
#        TableName: 'Users'
#        StreamSpecification:
#          StreamViewType: NEW_IMAGE
#
#    UserIdsTable:
#      Type: 'AWS::DynamoDB::Table'
#      DeletionPolicy: Retain
#      Properties:
#        AttributeDefinitions:
#          -
#            AttributeName: id
#            AttributeType: S
#        KeySchema:
#          -
#            AttributeName: id
#            KeyType: HASH
#        ProvisionedThroughput:
#          ReadCapacityUnits: 10
#          WriteCapacityUnits: 10
#        TableName: 'UserIds'
#
#
#    FriendsTable:
#      Type: 'AWS::DynamoDB::Table'
#      DeletionPolicy: Retain
#      Properties:
#        AttributeDefinitions:
#          -
#            AttributeName: userId
#            AttributeType: S
#          -
#            AttributeName: friendId
#            AttributeType: S
#        KeySchema:
#          -
#            AttributeName: userId
#            KeyType: HASH
#          -
#            AttributeName: friendId
#            KeyType: RANGE
#        ProvisionedThroughput:
#          ReadCapacityUnits: 10
#          WriteCapacityUnits: 10
#        TableName: 'Friends'
#        StreamSpecification:
#          StreamViewType: NEW_IMAGE



#plugins:
#  - serverless-client-s3
#
#custom:
#  client:
#    bucketName: www.gitmax.cn
